{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "velero.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"

{{- end }}
