{{- if and .Values.credentials.useSecret (not .Values.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velero.fullname" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.credentials.secretContents }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key, $value := .Values.credentials.extraEnvVars }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end -}}
