{{- if .Values.serviceAccount.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero.serverServiceAccount" . }}
{{- if .Values.serviceAccount.server.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.server.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- end }}
