{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "velero.fullname" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  endpoints:
  - port: monitoring
    interval: {{ .Values.metrics.scrapeInterval }}
{{- end }}
