version: 2.1
orbs:
  architect: giantswarm/architect@0.8.15

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push velero-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "velero-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
